
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ravisha
 */
public class Hangman extends javax.swing.JFrame {

    /**
     * Creates new form Hangman
     */
    
    public int[] indflag;
    String s;
    int wordlen;
   
    public Hangman() {
        initComponents();
        setTitle("HANGMAN");
        this.setLocation(450, 200);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                this.addWindowListener(new java.awt.event.WindowAdapter() {
    
    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
         FirstMainFrame f=new FirstMainFrame();
           setVisible(false);
            f.setVisible(true);
                    
        }
    
});
        
        String[] wordlist = new String[]{"puzzle","button","pyjama","zombie","jumble","mosque","circle","square"};
        textField2.setVisible(false);
        textField3.setVisible(false);
        textField4.setVisible(false);
        textField5.setVisible(false);
        textField6.setVisible(false);
        textField7.setVisible(false);
        label2.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);
        label6.setVisible(false);
        label7.setVisible(false);
        int randindex = (int)( Math.random()*(wordlist.length) );
   s = wordlist[randindex];
  wordlen = s.length();
  indflag = new int[s.length()];
  for(int i=0;i<6;i++)
                {
                    indflag[i]=0;
                }
  int j = (int) (0.5*wordlen);
                                       
     
  for(int i=0; i<j; i++){
   int k =(int)(Math.random()*(wordlen-1));
   if(indflag[k] == 0){
    indflag[k] = 1;
   }
   else
    i--;
  
  }
               if(indflag[0]==1)
               {
                   label2.setVisible(true);
                   label2.setText(""+s.charAt(0));
               }
               else{
               textField2.setVisible(true);
               
               }
               if(indflag[1]==1)
               {
                   label3.setVisible(true);
                   label3.setText(""+s.charAt(1));
               }
               else
               {
                   textField3.setVisible(true);
               }
               if(indflag[2]==1)
               {
                   label4.setVisible(true);
                   label4.setText(""+s.charAt(2));
               }
                else
               {
                   textField4.setVisible(true);
               }
               if(indflag[3]==1)
               {
                   label5.setVisible(true);
                   label5.setText(""+s.charAt(3));
               }
                else
               {
                   textField5.setVisible(true);
               }
               if(indflag[4]==1)
               {
                   label6.setVisible(true);
                   label6.setText(""+s.charAt(4));
               }
                else
               {
                   textField7.setVisible(true);
               }
               if(indflag[5]==1)
               {
                   label7.setVisible(true);
                   label7.setText(""+s.charAt(5));
               }
                else
               {
                   textField6.setVisible(true);
               }
               
               
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        label5 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label7 = new java.awt.Label();
        label6 = new java.awt.Label();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textField3 = new java.awt.TextField();
        textField5 = new java.awt.TextField();
        textField4 = new java.awt.TextField();
        textField7 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        textField6 = new java.awt.TextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravisha\\Desktop\\Pics\\JavaP\\hgggmn.PNG")); // NOI18N
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, 0, 580, 120);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, -2, 580, 130);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravisha\\Desktop\\Pics\\JavaP\\Bkfinal.PNG")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(480, 300, 60, 50);

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setBackground(new java.awt.Color(0, 51, 51));
        label5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setName("label5"); // NOI18N
        jPanel1.add(label5);
        label5.setBounds(380, 180, 50, 40);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(0, 51, 51));
        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setName("label2"); // NOI18N
        jPanel1.add(label2);
        label2.setBounds(200, 180, 50, 40);
        label2.getAccessibleContext().setAccessibleName("label2");

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(0, 51, 51));
        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setName("label3"); // NOI18N
        jPanel1.add(label3);
        label3.setBounds(260, 180, 50, 40);
        label3.getAccessibleContext().setAccessibleName("label3");

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setBackground(new java.awt.Color(0, 51, 51));
        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setName("label4"); // NOI18N
        jPanel1.add(label4);
        label4.setBounds(320, 180, 50, 40);
        label4.getAccessibleContext().setAccessibleName("label4");

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setBackground(new java.awt.Color(0, 51, 51));
        label7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setName("label7"); // NOI18N
        jPanel1.add(label7);
        label7.setBounds(500, 180, 50, 40);
        label7.getAccessibleContext().setAccessibleName("label7");

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setBackground(new java.awt.Color(0, 51, 51));
        label6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setName("label6"); // NOI18N
        jPanel1.add(label6);
        label6.setBounds(440, 180, 50, 40);
        label6.getAccessibleContext().setAccessibleName("label6");

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravisha\\Desktop\\Pics\\JavaP\\reff.PNG")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(480, 240, 50, 50);

        jLabel4.setBackground(new java.awt.Color(255, 153, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("7");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(310, 300, 130, 40);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravisha\\Desktop\\Pics\\JavaP\\submit.PNG")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 240, 120, 40);

        textField3.setBackground(new java.awt.Color(0, 51, 51));
        textField3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textField3.setForeground(new java.awt.Color(255, 255, 255));
        textField3.setVisible(false);
        jPanel1.add(textField3);
        textField3.setBounds(260, 180, 50, 40);

        textField5.setBackground(new java.awt.Color(0, 51, 51));
        textField5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textField5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(textField5);
        textField5.setBounds(380, 180, 50, 40);

        textField4.setBackground(new java.awt.Color(0, 51, 51));
        textField4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textField4.setForeground(new java.awt.Color(255, 255, 255));
        textField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField4ActionPerformed(evt);
            }
        });
        jPanel1.add(textField4);
        textField4.setBounds(320, 180, 50, 40);

        textField7.setBackground(new java.awt.Color(0, 51, 51));
        textField7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textField7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(textField7);
        textField7.setBounds(440, 180, 50, 40);

        textField2.setBackground(new java.awt.Color(0, 51, 51));
        textField2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textField2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(textField2);
        textField2.setBounds(200, 180, 50, 40);

        textField6.setBackground(new java.awt.Color(0, 51, 51));
        textField6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textField6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(textField6);
        textField6.setBounds(500, 180, 50, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravisha\\Desktop\\Pics\\JavaP\\hg0.PNG")); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 20, 110, 190);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 120, 190, 250);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravisha\\Desktop\\Pics\\JavaP\\white.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String check = "";
          int flag = 1;
        if(indflag[0]==1)
            {
              check = check + s.charAt(0);
            }
        else
        {
            if(textField2.getText().equals(""))
                {
                    check = check + s.charAt(0);
                    flag = 0;
                }
            else
                {
                    check = check + textField2.getText();
                }
        }
         if(indflag[1]==1)
            {
              check = check + s.charAt(1);
            }
        else
        {
            if(textField3.getText().equals(""))
                {
                    check = check + s.charAt(1);
                    flag = 0;
                }
            else
                {
                    check = check + textField3.getText();
                }
        }
         if(indflag[2]==1)
            {
              check = check + s.charAt(2);
            }
        else
        {
            if(textField4.getText().equals(""))
                {
                    check = check + s.charAt(2);
                    flag = 0;
                }
            else
                {
                    check = check + textField4.getText();
                }
        }
          if(indflag[3]==1)
            {
              check = check + s.charAt(3);
            }
        else
        {
            if(textField5.getText().equals(""))
                {
                    check = check + s.charAt(3);
                    flag = 0;
                }
            else
                {
                    check = check + textField5.getText();
                }
        }
        if(indflag[4]==1)
            {
              check = check + s.charAt(4);
            }
        else
        {
            if(textField7.getText().equals(""))
                {
                    check = check + s.charAt(4);
                    flag = 0;
                }
            else
                {
                    check = check + textField7.getText();
                }
        }
         if(indflag[5]==1)
            {
              check = check + s.charAt(5);
            }
        else
        {
            if(textField6.getText().equals(""))
                {
                    check = check + s.charAt(5);
                    flag = 0;
                }
            else
                {
                    check = check + textField6.getText();
                }
        }
         System.out.println(check);
         System.out.println(s);
         System.out.println(check.equals(s));
          //System.out.println(check);
        if(!check.equals(s))
        {
            if(jLabel4.getText().equals("7")){
                jLabel4.setText("6");
                jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravisha\\Desktop\\Pics\\JavaP\\hg1.PNG"));
                //jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/hangman1.png")));
            //System.out.println("entered here");
            }
            else if(jLabel4.getText().equals("6")){
                jLabel4.setText("5");
                jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravisha\\Desktop\\Pics\\JavaP\\hg2.PNG"));
//jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/hangman2.png")));
            
            }
            else if(jLabel4.getText().equals("5")){
                jLabel4.setText("4");
                //jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/hangman3.png")));
                jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravisha\\Desktop\\Pics\\JavaP\\hg3.PNG"));
            }
            else if(jLabel4.getText().equals("4")){
                jLabel4.setText("3");
                jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravisha\\Desktop\\Pics\\JavaP\\hg4.PNG"));
                //jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/hangman4.png")));
            }
            else if(jLabel4.getText().equals("3")){
                jLabel4.setText("2");
                jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravisha\\Desktop\\Pics\\JavaP\\hg5.PNG"));
                //jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/hangman5.png")));
            }
            else if(jLabel4.getText().equals("2")){
                jLabel4.setText("1");
                jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravisha\\Desktop\\Pics\\JavaP\\hg6.PNG"));
                //jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/hangman6.png")));
            
            }
             else if(jLabel4.getText().equals("1")){
                jLabel4.setText("GAME OVER :(");
                jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravisha\\Desktop\\Pics\\JavaP\\hg7.PNG"));
                //jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/hangman7.png")));
            
            }
            
            
                
        }
        else if(flag==1)
        {
            jLabel4.setText("You Won");
        }
            
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        FirstMainFrame sec=new FirstMainFrame();
        sec.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       setVisible(false);
        Hangman sec=new Hangman();
        sec.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hangman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    private java.awt.TextField textField6;
    private java.awt.TextField textField7;
    // End of variables declaration//GEN-END:variables
}
